version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm run serve
  json-server:
      build: ./json-server
      ports:
        - '3000:3000'
      volumes: 
        - .:/data/json-server
      command: json-server --watch ./json-server/db.json --host 0.0.0.0