export const DRAWER_UPDATE = 'DRAWER_UPDATE'
export const FETCH_GAMES = 'FETCH_GAMES'
export const FETCH_GAME = 'FETCH_GAME'
export const FETCH_RSS = 'FETCH_RSS'
export const FETCH_PLAYERS = 'FETCH_PLAYERS'
